name: pokerd
description: A command line Texas Hold'em implementation.
version: 1.0.7
homepage: https://github.com/filiph/pokerd
repository: https://github.com/filiph/pokerd

environment:
  sdk: '>=3.11.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ansi_escapes: ^2.0.1  # For low-level ANSI escape codes, like cursor movement
  args: ^2.7.0
  logging: ^1.2.0
  meta: ^1.8.0
  tint: ^2.0.1  # For ANSI color support

dev_dependencies:
  cli_pkg: ^2.15.1
  grinder: ^0.9.5
  lints: ^6.0.0
  test: ^1.25.6

executables:
  pokerd: pokerd
